name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node / Python (if needed)
      run: echo "Setup your runtime here"

    - name: Run Tests
      run: |
        echo "Run your tests here"
        # example:
        # npm install
        # npm test

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Generate Tests using AI
      run: python ai_generate_tests.py
      env:
       OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Commit tests
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add test_app.py
        git commit -m "Add AI-generated tests" || echo "No changes"
        git push

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: terraform
      run: terraform init

    - name: Terraform Validate
      working-directory: terraform
      run: terraform validate

    - name: Terraform Plan
      working-directory: terraform
      run: terraform plan -var="image_uri=dummy-image"